// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0K40HE1CknHFhT4DPJL9ymyat4jkoc8s',
    appId: '1:906037402424:web:14ee701d769b5a28083fcd',
    messagingSenderId: '906037402424',
    projectId: 'readarc-2',
    authDomain: 'readarc-2.firebaseapp.com',
    storageBucket: 'readarc-2.appspot.com',
    measurementId: 'G-CNX9QWPCJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj5hO8TfltQB-PA7oKOnvekd85vkT7zvU',
    appId: '1:906037402424:android:d4068751e03e68ed083fcd',
    messagingSenderId: '906037402424',
    projectId: 'readarc-2',
    storageBucket: 'readarc-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtrRGWeOZaOd82uvxfqhQbc0-EshWrHyg',
    appId: '1:906037402424:ios:4938a3e1f544105f083fcd',
    messagingSenderId: '906037402424',
    projectId: 'readarc-2',
    storageBucket: 'readarc-2.appspot.com',
    iosBundleId: 'com.example.readarcAdminApk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtrRGWeOZaOd82uvxfqhQbc0-EshWrHyg',
    appId: '1:906037402424:ios:4938a3e1f544105f083fcd',
    messagingSenderId: '906037402424',
    projectId: 'readarc-2',
    storageBucket: 'readarc-2.appspot.com',
    iosBundleId: 'com.example.readarcAdminApk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0K40HE1CknHFhT4DPJL9ymyat4jkoc8s',
    appId: '1:906037402424:web:49b1c2eb59349250083fcd',
    messagingSenderId: '906037402424',
    projectId: 'readarc-2',
    authDomain: 'readarc-2.firebaseapp.com',
    storageBucket: 'readarc-2.appspot.com',
    measurementId: 'G-LHZGDQD3R3',
  );
}
